from django.urls import path

from .views import (
    admin_sign_video_detail,
    admin_sign_videos,
    admin_user_details,
    admin_user_status,
    admin_users,
    award_certificate,
    check_session,
    csrf_token,
    game_level_item_detail,
    game_level_items,
    health_check,
    instructor_announcement_detail,
    instructor_announcements,
    instructor_dashboard,
    instructor_game_level_detail,
    instructor_game_levels,
    instructor_module_detail,
    instructor_modules,
    instructor_upload_sign_video,
    logout,
    module_quiz_question_detail,
    module_quiz_questions,
    module_quiz_submit,
    leaderboard,
    learning_state,
    login,
    module_file_detail,
    module_files,
    public_announcements,
    predict_fingerspelling,
    predict_sign,
    predict_word_sequence,
    public_game_levels,
    recent_predictions,
    request_password_reset,
    resend_password_reset_code,
    resend_verification,
    reset_password,
    verify_email,
    sign_videos,
    student_content,
    profile_photo,
    profile_update,
    signup,
    user_certificates,
)

urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("auth/signup/", signup, name="auth-signup"),
    path("auth/login/", login, name="auth-login"),
    path("auth/logout/", logout, name="auth-logout"),
    path("auth/me/", check_session, name="auth-check-session"),
    path("auth/csrf/", csrf_token, name="auth-csrf-token"),
    path("auth/verify-email/", verify_email, name="auth-verify-email"),
    path("auth/resend-verification/", resend_verification, name="auth-resend-verification"),
    path("auth/request-password-reset/", request_password_reset, name="auth-request-password-reset"),
    path("auth/resend-password-reset-code/", resend_password_reset_code, name="auth-resend-password-reset-code"),
    path("auth/reset-password/", reset_password, name="auth-reset-password"),
    path("leaderboard/", leaderboard, name="leaderboard"),
    path("announcements/", public_announcements, name="public-announcements"),
    path("learning/state/", learning_state, name="learning-state"),
    path("certificates/", user_certificates, name="user-certificates"),
    path("certificates/award/", award_certificate, name="certificate-award"),
    path("student/content/", student_content, name="student-content"),
    path("profile/photo/", profile_photo, name="profile-photo"),
    path("profile/update/", profile_update, name="profile-update"),
    path("instructor/dashboard/", instructor_dashboard, name="instructor-dashboard"),
    path("instructor/modules/", instructor_modules, name="instructor-modules"),
    path("instructor/modules/<int:module_id>/", instructor_module_detail, name="instructor-module-detail"),
    path("instructor/modules/<int:module_id>/quiz/", module_quiz_questions, name="module-quiz-questions"),
    path("instructor/modules/<int:module_id>/quiz/<int:question_id>/", module_quiz_question_detail, name="module-quiz-question-detail"),
    path("modules/<int:module_id>/submit_quiz/", module_quiz_submit, name="module-quiz-submit"),
    path("instructor/modules/<int:module_id>/files/", module_files, name="module-files"),
    path("instructor/modules/<int:module_id>/files/<int:file_id>/", module_file_detail, name="module-file-detail"),
    path("instructor/announcements/", instructor_announcements, name="instructor-announcements"),
    path("instructor/announcements/<int:announcement_id>/", instructor_announcement_detail, name="instructor-announcement-detail"),
    path("instructor/game-levels/", instructor_game_levels, name="instructor-game-levels"),
    path("instructor/game-levels/<int:level_id>/", instructor_game_level_detail, name="instructor-game-level-detail"),
    path("instructor/game-levels/<int:level_id>/items/", game_level_items, name="game-level-items"),
    path("instructor/game-levels/<int:level_id>/items/<int:item_id>/", game_level_item_detail, name="game-level-item-detail"),
    path("instructor/sign-videos/", instructor_upload_sign_video, name="instructor-upload-sign-video"),
    path("games/<str:game_key>/levels/", public_game_levels, name="public-game-levels"),
    path("admin/users/", admin_users, name="admin-users"),
    path("admin/users/<int:user_id>/", admin_user_details, name="admin-user-details"),
    path("admin/users/<int:user_id>/status/", admin_user_status, name="admin-user-status"),
    path("admin/sign-videos/", admin_sign_videos, name="admin-sign-videos"),
    path("admin/sign-videos/<int:video_id>/", admin_sign_video_detail, name="admin-sign-video-detail"),
    path("sign/predict/", predict_sign, name="predict-sign"),
    path("sign/fingerspell/", predict_fingerspelling, name="predict-fingerspelling"),
    path("sign/word-sequence/", predict_word_sequence, name="predict-word-sequence"),
    path("sign/recent/", recent_predictions, name="recent-predictions"),
    path("sign-videos/", sign_videos, name="sign-videos"),
]
