# Generated by Django 5.1.2 on 2026-05-21 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0009_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='fas fa-gamepad', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GameDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.CharField(max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficulties', to='signtext.game')),
            ],
            options={
                'ordering': ['year_level', 'difficulty'],
                'unique_together': {('game', 'year_level', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='signtext.gamedifficulty')),
            ],
            options={
                'ordering': ['level_number'],
                'unique_together': {('difficulty', 'level_number')},
            },
        ),
        migrations.CreateModel(
            name='GameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_game_content', to=settings.AUTH_USER_MODEL)),
                ('game_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='signtext.gamelevel')),
            ],
            options={
                'verbose_name': 'Game Content',
                'verbose_name_plural': 'Game Content Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
