# Generated by Django 5.1.2 on 2026-05-21 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0010_game_gamedifficulty_gamelevel_gamecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('identification', 'Identification')], default='multiple_choice', max_length=30)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='signtext.learningmodule')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
