# Generated by Django 5.1.2 on 2026-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0011_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('suffix', models.CharField(blank=True, default='', max_length=32)),
                ('full_name', models.CharField(max_length=120)),
                ('year_level', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(default='student', max_length=20)),
                ('password_hash', models.CharField(max_length=256)),
                ('otp', models.CharField(max_length=8)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gamedifficulty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gamedifficulty',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamecontent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gamecontent',
            name='game_level',
        ),
        migrations.AlterUniqueTogether(
            name='gamelevel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gamelevel',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='GameContent',
        ),
        migrations.DeleteModel(
            name='GameDifficulty',
        ),
        migrations.DeleteModel(
            name='GameLevel',
        ),
    ]
