# Generated by Django 5.1.2 on 2026-07-09 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0012_pendingemailverification_remove_gamedifficulty_game_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField(choices=[('sign_match', 'Sign Match Game'), ('typing', 'Sign-to-Word Typing Game'), ('sentence', 'Sentence Builder Game'), ('scenario', 'Scenario-Based Game')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('level_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_game_levels', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_game_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['game_key', 'difficulty', 'level_number'],
                'unique_together': {('game_key', 'difficulty', 'level_number')},
            },
        ),
        migrations.CreateModel(
            name='GameLevelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('answer', models.CharField(blank=True, default='', max_length=255)),
                ('media_url', models.CharField(blank=True, default='', max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='signtext.gamelevel')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
