# Generated by Django 5.1.2 on 2026-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0013_gamelevel_gamelevelitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('word', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('alphabet', 'Alphabet'), ('emotions', 'Emotions'), ('everyday_words', 'Everyday Words'), ('expressions', 'Expressions'), ('greetings', 'Greetings'), ('phrases', 'Phrases'), ('responses', 'Responses')], default='phrases', max_length=30)),
                ('video', models.FileField(upload_to='sign_videos/%Y/%m/%d/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'word'],
            },
        ),
    ]
