# Generated by Django 5.1.2 on 2026-07-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0014_signvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideo',
            name='text_to_sign_only',
            field=models.BooleanField(default=False),
        ),
    ]
