# Generated by Django 5.1.2 on 2026-07-31 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0019_seed_sentence_scenario_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField(choices=[('sign_match', 'Sign Match Game'), ('typing', 'Sign-to-Word Typing Game'), ('sentence', 'Sentence Builder Game'), ('scenario', 'Scenario-Based Game')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('template_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/%Y/%m/')),
                ('student_name', models.CharField(max_length=150)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('emailed', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='signtext.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'certificate')},
            },
        ),
    ]
