# Generated by Django 5.1.2 on 2026-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0024_reshape_sentence_scenario_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSL105Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(db_index=True, max_length=150)),
                ('category', models.CharField(blank=True, default='', max_length=150)),
                ('split', models.CharField(choices=[('train', 'Train'), ('test', 'Test')], max_length=10)),
                ('source_path', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='fsl105_clips/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['label', 'clip_id'],
            },
        ),
    ]
