# Generated by Django 5.1.2 on 2026-09-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0025_fsl105clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fsl105clip',
            name='video',
        ),
        migrations.AddField(
            model_name='fsl105clip',
            name='video_content_type',
            field=models.CharField(blank=True, default='video/quicktime', max_length=100),
        ),
        migrations.AddField(
            model_name='fsl105clip',
            name='video_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='fsl105clip',
            name='video_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
