# Generated by Django 5.1.2 on 2026-09-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0026_remove_fsl105clip_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signvideo',
            name='category',
            field=models.CharField(choices=[('alphabet', 'Alphabet'), ('emotions', 'Emotions'), ('everyday_words', 'Everyday Words'), ('expressions', 'Expressions'), ('greetings', 'Greetings'), ('phrases', 'Phrases'), ('responses', 'Responses'), ('calendar', 'Calendar'), ('colors', 'Colors'), ('numbers', 'Numbers'), ('days', 'Days'), ('family', 'Family'), ('relationships', 'Relationships'), ('food', 'Food'), ('drink', 'Drink'), ('survival', 'Survival')], default='phrases', max_length=30),
        ),
    ]
