# Generated by Django 5.1.2 on 2026-09-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0028_expand_game_level_databank'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='module',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='signtext.learningmodule'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='game_key',
            field=models.CharField(blank=True, choices=[('sign_match', 'Sign Match Game'), ('typing', 'Sign-to-Word Typing Game'), ('sentence', 'Sentence Builder Game'), ('scenario', 'Scenario-Based Game')], max_length=20, null=True, unique=True),
        ),
    ]
