# Generated by Django 5.1.2 on 2026-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0029_certificate_module_alter_certificate_game_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='signvideo',
            name='video_content_type',
            field=models.CharField(blank=True, default='video/mp4', max_length=100),
        ),
        migrations.AddField(
            model_name='signvideo',
            name='video_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='signvideo',
            name='video_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='video',
            field=models.FileField(blank=True, upload_to='sign_videos/%Y/%m/%d/'),
        ),
    ]
