# Generated by Django 5.1.2 on 2026-09-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signtext', '0030_signvideo_video_content_type_signvideo_video_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signvideo',
            name='video_content_type',
        ),
        migrations.RemoveField(
            model_name='signvideo',
            name='video_data',
        ),
        migrations.RemoveField(
            model_name='signvideo',
            name='video_filename',
        ),
        migrations.AlterField(
            model_name='signvideo',
            name='video',
            field=models.FileField(upload_to='sign_videos/%Y/%m/%d/'),
        ),
    ]
